### ISSUE TITLE
Read-only server

### ISSUE THREAD

**Issue by 1ace** [steiza/simplepypi#13]
Hi!

I'm currently evaluating ways to provide in-house packages and this looks like a good option, but having any of the employees able to upload packages doesn't sound very good (a mistake happens easily).

I had a quick look through the code, and I think simply deleting `IndexHandler::post()` should be enough? Is there anything else that needs to be done?

Thanks for writing this light pypi server!

**Comment by steiza** [comment]
Hello!

Yeah, there's a bunch of different ways you could do this.

One way would be like you're suggesting on https://github.com/pypiserver/pypiserver/issues/337 - you could copy the packages into place manually, and then disable `IndexHandler::post()` to prevent people from submitting via HTTP.

Another way to do it would be to put something in front of `simplepypi`, like `nginx` and to not allow POSTs (or only allow POSTs that meet certain conditions) with your `nginx` config. Or if you're in AWS you could use something like API Gateway.

Good luck!
